name: Rupesh's Blog
description: This is where I will tell my friends way too much about me
meta_description: "Rupesh's Blog, This is where I will tell my friends way too much about me"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog.irupesh.com1/
domain_name: 'http://blog.irupesh.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
permalink: /:title.html

# Details for the RSS feed generator
url:            'blog.irupesh.com'
author:         'Rupesh Ranjan'
